[2024-10-29 14:49:20,268] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-10-28T00:00:00+00:00 [queued]>
[2024-10-29 14:49:20,272] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-10-28T00:00:00+00:00 [queued]>
[2024-10-29 14:49:20,273] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:49:20,273] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-29 14:49:20,273] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 14:49:20,289] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2024-10-28 00:00:00+00:00
[2024-10-29 14:49:20,290] {standard_task_runner.py:52} INFO - Started process 110500 to run task
[2024-10-29 14:49:20,292] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2024-10-28T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', '/root/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpig_ag0mo', '--error-file', '/tmp/tmp5nyk153p']
[2024-10-29 14:49:20,293] {standard_task_runner.py:80} INFO - Job 35: Subtask run_after_loop
[2024-10-29 14:49:20,316] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-10-28T00:00:00+00:00 [running]> on host LAPTOP-SNAE0A1O.
[2024-10-29 14:49:20,351] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2024-10-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-28T00:00:00+00:00
[2024-10-29 14:49:20,351] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-29 14:49:20,352] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2024-10-29 14:49:20,356] {subprocess.py:85} INFO - Output:
[2024-10-29 14:49:20,356] {subprocess.py:92} INFO - 1
[2024-10-29 14:49:20,357] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-29 14:49:20,373] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20241028T000000, start_date=20241029T174920, end_date=20241029T174920
[2024-10-29 14:49:20,423] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-29 14:49:20,435] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
